import antigravity

CERT="""-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACBZ5NOqHIkXvKD7WBT2p5RBHzC6PN1swnonezQv8HO5owAAAJDJQWivyUFo
rwAAAAtzc2gtZWQyNTUxOQAAACBZ5NOqHIkXvKD7WBT2p5RBHzC6PN1swnonezQv8HO5ow
AAAEDcB9ELF/KnNS2sEHLCLd7tE6Ahh/dE1dpClpu3gMkLn1nk06ociRe8oPtYFPanlEEf
MLo83WzCeid7NC/wc7mjAAAABm15LWtleQECAwQFBgc=
-----END OPENSSH PRIVATE KEY-----
"""

def main():
    antigravity.fly()

if __name__ == "__main__":
    main()
